spring:
  profiles:
    default: local
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
  redis:
    port: 16379
    host: localhost
  mvc:
    format:
      date: yyyy-MM-dd
jwt:
  secret-key: ENC(z1qhyistBmY+rofD3eB2jHFMtMfPLVFbGFxgLQ3n1hU=)
  access-expiration-time: 3600000
  refresh-expiration-time: 604800000
  refresh-valid-time: 259200000
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_MEERON_PASSWORD}
    property:
      prefix: ENC(
      suffix: )
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod