# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build With Gradle
        run: ./gradlew clean build -i -Pjasypt.encryptor.password=${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
      - name: Make Directory for Deliver
        run: mkdir deploy
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy/
      - name: Copy Dockerfile
        run: cp Dockerfile ./deploy/
      - name: Copy appspec
        run: cp appspec.yml ./deploy/
      - name: Copy shell
        run: cp ./scripts/* ./deploy/
      - name: Make Zip File
        run: zip -r -qq -j ./app.zip ./deploy
      - name: Deliver to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          ./app.zip s3://meeron-bucket/build/
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name meeron-codedeploy \
          --deployment-group-name meeron-dev-codedeploy-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=meeron-bucket,bundleType=zip,key=build/app.zip \
          --region ap-northeast-2
      - name: build result to slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{job.status}}
          fields: all
          author_name: 'meeron CI / CD'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
